---
name: Build

"on":
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v2

      - name: Install libncurses5
        run: apt-get update && apt-get install -y libncurses5-dev

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: make test

      - name: Run build
        run: make build
